---
# tasks file for /etc/ansible/roles/apache
- name: Install httpd Package
  yum: name=httpd state=latest
- name: Copy index.html file
  copy: src=/data/index.html dest=/var/www/html
  notify:
  - restart apache
#- name: Start and Enable httpd service
 # service: name=httpd state=restarted enabled=yes
